# Generated by Django 3.1.5 on 2021-05-31 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrgList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('okpo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('func', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('respons_person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.responsperson')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbrev', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StorageMat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=10, max_digits=19)),
                ('mat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.mat')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.storage')),
            ],
        ),
        migrations.CreateModel(
            name='MatDepart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('count', models.DecimalField(decimal_places=10, max_digits=19)),
                ('mat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.mat')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.orglist')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.storage')),
            ],
        ),
        migrations.CreateModel(
            name='MatComing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('count', models.DecimalField(decimal_places=10, max_digits=19)),
                ('mat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.mat')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.orglist')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.storage')),
            ],
        ),
        migrations.AddField(
            model_name='mat',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.unit'),
        ),
    ]
